# Changes here will be overwritten by Copier
_commit: 2025.3.0-80-g0147440
_src_path: https://github.com/ninerealmlabs/precommit-template
conventional_commits: true
docker: true
editorconfig: true
markdown: true
prettier: true
python: true
shell: true
typos: true
yaml: true
